export enum ResponseCode {
  OK = '200000',
  BAD_REQUEST = '400000',
  MISSING_MANDATORY_FIELD = '400001',
  INVALID_FIELD_FORMAT = '400002',
  RESOURCE_ALREADY_EXISTS = '400003',
  INSUFFICIENT_BALANCE = '400004',
  REQUEST_IN_PROGRESS = '400005',
  TOO_MANY_ATTEMPTS = '400006',
  LOGIN_FAILED = '400007',
  USER_SUSPENDED = '400008',
  INVALID_FILE_TYPE = '400009',
  INVALID_PAYMENT_AMOUNT = '400010',
  EMAIL_NO_VERIFIED = '400011',
  RESOURCE_NOT_FOUND = '400012',
  NOT_FOUND = '402012',
  INTERNAL_SERVER_ERROR = '5000000',
}

export const ResponseMessage: Record<ResponseCode, string> = {
  [ResponseCode.OK]: 'OK',
  [ResponseCode.BAD_REQUEST]: 'Bad request',
  [ResponseCode.MISSING_MANDATORY_FIELD]: 'Missing mandatory field',
  [ResponseCode.INVALID_FIELD_FORMAT]: 'Invalid field format',
  [ResponseCode.RESOURCE_ALREADY_EXISTS]: 'Resource already exists',
  [ResponseCode.INSUFFICIENT_BALANCE]: 'Insufficient balance',
  [ResponseCode.REQUEST_IN_PROGRESS]: 'Request in progress',
  [ResponseCode.TOO_MANY_ATTEMPTS]: 'Too many attempts',
  [ResponseCode.LOGIN_FAILED]: 'Login failed',
  [ResponseCode.USER_SUSPENDED]: 'User suspended',
  [ResponseCode.INVALID_FILE_TYPE]: 'Invalid file type',
  [ResponseCode.INVALID_PAYMENT_AMOUNT]: 'Invalid payment amount',
  [ResponseCode.EMAIL_NO_VERIFIED]: 'Email no verified',
  [ResponseCode.RESOURCE_NOT_FOUND]: 'Resource not found',
  [ResponseCode.NOT_FOUND]: 'Not found',
  [ResponseCode.INTERNAL_SERVER_ERROR]: 'Internal server error',
};
